# Generated by Django 4.2.2 on 2023-06-16 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AOTYAlbum',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('critic_score', models.IntegerField(blank=True, null=True)),
                ('user_score', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('spotify_link', models.URLField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=64, null=True)),
                ('genres', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Album of the Year album',
            },
        ),
        migrations.CreateModel(
            name='AOTYArtist',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Album of the Year artist',
            },
        ),
        migrations.CreateModel(
            name='AOTYAlbumRating',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.aotyalbum')),
            ],
            options={
                'verbose_name': 'Album of the Year album rating',
            },
        ),
        migrations.AddField(
            model_name='aotyalbum',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.aotyartist'),
        ),
    ]
