# Generated by Django 4.2.2 on 2023-06-17 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AOTYAlbum',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('critic_score', models.IntegerField(blank=True, null=True)),
                ('user_score', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('spotify_link', models.URLField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=64, null=True)),
                ('genres', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AOTY album',
            },
        ),
        migrations.CreateModel(
            name='AOTYAlbumPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('page', models.TextField()),
            ],
            options={
                'verbose_name': 'AOTY album page',
            },
        ),
        migrations.CreateModel(
            name='AOTYAlbumRating',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.aotyalbum')),
            ],
            options={
                'verbose_name': 'AOTY album rating',
            },
        ),
        migrations.AddField(
            model_name='aotyalbum',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.aotyalbumpage'),
        ),
    ]
