# Generated by Django 4.2.2 on 2023-06-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_aotyalbumpage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AOTYArtist',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'AOTY Artist',
            },
        ),
        migrations.CreateModel(
            name='AOTYGenre',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'AOTY Genre',
            },
        ),
        migrations.AlterModelOptions(
            name='aotyalbum',
            options={'verbose_name': 'AOTY Album'},
        ),
        migrations.AlterModelOptions(
            name='aotyalbumpage',
            options={'verbose_name': 'AOTY Album Page'},
        ),
        migrations.AlterModelOptions(
            name='aotyalbumrating',
            options={'verbose_name': 'AOTY Album Rating'},
        ),
        migrations.AddField(
            model_name='aotyalbum',
            name='artists',
            field=models.ManyToManyField(blank=True, null=True, to='warehouse.aotyartist'),
        ),
    ]
