# Generated by Django 4.2.2 on 2023-06-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_aotyartist_aotygenre_alter_aotyalbum_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aotyalbum',
            name='artists',
            field=models.ManyToManyField(blank=True, to='warehouse.aotyartist'),
        ),
        migrations.RemoveField(
            model_name='aotyalbum',
            name='genres',
        ),
        migrations.AddField(
            model_name='aotyalbum',
            name='genres',
            field=models.ManyToManyField(blank=True, to='warehouse.aotygenre'),
        ),
    ]
