# Generated by Django 4.2.2 on 2023-06-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_aotyalbum_artists_alter_aotyalbum_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aotyalbum',
            name='artists',
            field=models.ManyToManyField(related_name='albums', to='warehouse.aotyartist'),
        ),
        migrations.AlterField(
            model_name='aotyalbum',
            name='genres',
            field=models.ManyToManyField(related_name='albums', to='warehouse.aotygenre'),
        ),
    ]
