# Generated by Django 4.2.2 on 2023-06-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_aotyalbum_artists_alter_aotyalbum_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aotyalbum',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='albums', to='warehouse.aotygenre'),
        ),
    ]
