# Generated by Django 4.2.2 on 2023-06-19 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_alter_aotyalbum_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aotyalbumpage',
            name='url',
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
