# Generated by Django 4.2.2 on 2023-06-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_alter_aotyalbumpage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aotyalbumpage',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
