# Generated by Django 4.2.2 on 2023-06-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_alter_aotyalbumpage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aotyartist',
            name='name',
            field=models.CharField(max_length=2000),
        ),
    ]
