# Generated by Django 4.2.2 on 2023-06-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_alter_aotyartist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aotyalbum',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
